### PR TITLE
Add safearea.get_insets()

### PR DESCRIPTION
**Pull request by dapetcu21**
Note: I couldn't test this on a notched device (I don't have one of the fancy new iPhones and Simulator builds are broken).

### CODE REVIEW

**Comment by dapetcu21** [comment]
Ping @britzl?

**Comment by britzl** [comment]
Oh, sorry, I missed this PR! I don't have access to any iOS devices this week so I can't test. I'll do it first thing on Monday next week.

**Comment by britzl** [comment]
I'm getting insets of 0 (top, left, right and bottom) when testing on an iPhone X with iOS 14.0

**Comment by dapetcu21** [comment]
Weird. Did you set `safearea.resize_game_view = 0`?

**Comment by britzl** [comment]
> Weird. Did you set `safearea.resize_game_view = 0`

Erm, no 🤦 . Let me retest!

**Comment by britzl** [comment]
It works!

**Pull request merged**
